import type {Metadata} from 'next';
import Link from 'next/link';
import Image from 'next/image';
import Reveal from '@/components/Reveal';
import BrandOrigin from '@/components/BrandOrigin';
import {SITE,TEAM,PROGRAMS} from '@/lib/content';
import {FOUNDING_STORY,PUBLIC_RESEARCH} from '@/lib/publicStory';
export const metadata:Metadata={title:'Our Story',description:'Meet KritRNA by Transloka Bio: our purpose, founders, translation-biology foundation and India-built ambition.'};
const principles=[['Scientific truth before narrative','Build compelling communication on precise, attributable evidence. Distinguish a result, an inference and a question still being tested.'],['Evidence gates before timelines','Advance programmes through reproducible measurements and disease-relevant questions rather than visual percentages or arbitrary deadlines.'],['Patients are people','Respect privacy, autonomy and the boundary between education, research and clinical care. Make difficult science understandable without promising an outcome.'],['Build capability from India','Develop scientific ownership and durable infrastructure while collaborating with researchers, development partners and communities around the world.']];
export default function About(){return <div className="noir-about"><section className="page-hero"><div className="wrap"><Reveal><div className="eyebrow">ABOUT KRITRNA / {SITE.legal}</div><h1 className="h1">A question from biology.<br/><em>A company built to pursue it.</em></h1><p className="lead">KritRNA is the scientific and public-facing brand of {SITE.legal}, based in Noida, India. We are developing suppressor-tRNA therapeutics and computational translation systems for selected diseases driven by premature stop codons.</p></Reveal></div></section><section><div className="wrap about-purpose"><Reveal><span className="micro">OUR PURPOSE</span><h2 className="display-heading smaller">Help the message<br/><em>become the protein.</em></h2></Reveal><Reveal><p className="large-body">The genetic code is not useful until the cell can read it. We work at that point of translation—where a molecular adaptor can make the difference between stopping and continuing.</p><p>Our mission is to design biologically informed suppressor-tRNA candidates and test whether they can restore useful protein expression in selected nonsense-mutation contexts. We bring together candidate design, systems thinking and experimental evidence because performance is shaped by more than the molecule alone.</p><p>Our initial research priorities are {PROGRAMS.map(p=>p.gene).join(', ')}. Our company is at an early preclinical research stage, with candidate design and experimental-validation planning guiding the next steps.</p><Link href="/platform" className="underline-link">Explore what we are building ↗</Link></Reveal></div></section><BrandOrigin about/>
 <section id="founding-story" className="founding-story"><div className="wrap"><div className="section-index"><span>THE FOUNDING STORY</span><span>RESEARCH → PURPOSE → CAPABILITY</span></div><div className="founding-layout"><Reveal><div className="story-portrait"><Image src={TEAM.lead.photo} alt="Dr. Nikhil Bharti" width={500} height={620} sizes="(max-width: 700px) 85vw, 420px"/></div><p className="portrait-label">DR. NIKHIL BHARTI<br/>Scientific Co-Founder & Director</p></Reveal><div><Reveal><h2 className="display-heading smaller">From understanding translation<br/><em>to engineering possibility.</em></h2></Reveal>{FOUNDING_STORY.map((p,i)=><Reveal key={i}><p className={i===0?'large-body':''}>{p}</p></Reveal>)}<Reveal><a href={PUBLIC_RESEARCH.href} target="_blank" rel="noreferrer" className="underline-link">The 2024 research foundation ↗</a><p className="scene-note">Academic research and company development are distinct. Institutional affiliations identify research experience, not institutional endorsement or ownership by KritRNA of university intellectual property.</p></Reveal></div></div><div className="shared-foundation"><Reveal><span className="micro">A SHARED FOUNDING RESPONSIBILITY</span><h3>Science needs a human connection.</h3><p>Pragati Bhaisora, Co-Founder & Director, leads outreach, awareness, stakeholder communication and rare-disease community engagement. Alongside the scientific programme, this work creates the relationships and clarity needed to build a responsible biotechnology company.</p><Link href="/team" className="underline-link">Meet both founders and the scientific network ↗</Link></Reveal><Reveal><div className="story-portrait secondary-portrait"><Image src={TEAM.outreach.photo} alt="Pragati Bhaisora" width={420} height={500} sizes="(max-width: 700px) 70vw, 280px"/></div></Reveal></div></div></section>
 <section><div className="wrap"><div className="section-index"><span>OUR OPERATING PRINCIPLES</span><span>HOW PURPOSE BECOMES PRACTICE</span></div><div className="principle-spread">{principles.map(([title,text],i)=><Reveal key={title}><article><span className="micro">0{i+1}</span><h3>{title}</h3><p>{text}</p></article></Reveal>)}</div></div></section><section><div className="wrap split-2"><Reveal><h2 className="display-heading smaller">The company<br/><em>behind the science.</em></h2><p className="section-lead">KritRNA connects original scientific ambition with the work of building a durable company from India.</p><Link href="/contact" className="underline-link">Start a conversation ↗</Link></Reveal><dl className="company-facts">{[['Legal entity',SITE.legal],['Operating brand','KritRNA™'],['Location',SITE.location],['CIN',SITE.cin],['Research stage','Early preclinical research'],['Initial focus','HBB · DMD · TP53']].map(([title,value])=><div key={title}><dt>{title}</dt><dd>{value}</dd></div>)}</dl></div></section></div>;}
