import Link from 'next/link';
import PageIdentity from '@/components/PageIdentity';
import {pageMetadata,SEO_ORIGIN,jsonLd} from '@/lib/seo';
import './research-guide.css';

export const metadata=pageMetadata('/rna-research-india');
const sources=[
 {id:'rna-basics',name:'NHGRI: Ribonucleic acid (RNA)',url:'https://www.genome.gov/genetics-glossary/Ribonucleic-Acid-RNA'},
 {id:'rna-india',name:'RNA India: research network and community',url:'https://www.rnaindia.org/'},
 {id:'iisc',name:'IISc Biochemistry: Sandeep M. Eswarappa laboratory',url:'https://biochem.iisc.ac.in/sandeep-m-eswarappa.php'},
 {id:'ils',name:'Institute of Life Sciences: Amaresh C. Panda laboratory',url:'https://www.ils.res.in/scientists/amaresh-c-panda/'},
 {id:'igib',name:'CSIR-IGIB: RNA Biology laboratory and gene-therapy research',url:'https://www.igib.res.in/Gene_therapy'},
 {id:'velocity',name:'Bharti, Santos et al. (2024), Nature Communications: translation velocity and suppressor-tRNA efficacy',url:'https://www.nature.com/articles/s41467-024-47258-9'},
 {id:'engineered',name:'Albers et al. (2023), Nature: engineered tRNAs in cellular and in-vivo models',url:'https://www.nature.com/articles/s41586-023-06133-1'}
];
const article={'@context':'https://schema.org','@type':'Article','@id':`${SEO_ORIGIN}/rna-research-india#article`,headline:'RNA research in India: from translation biology to therapeutics',description:'A source-linked guide to selected Indian RNA research resources and KritRNA’s suppressor-tRNA research focus.',mainEntityOfPage:{'@id':`${SEO_ORIGIN}/rna-research-india#webpage`},author:{'@id':`${SEO_ORIGIN}/#organization`},publisher:{'@id':`${SEO_ORIGIN}/#organization`},datePublished:'2026-09-14',dateModified:'2026-09-14',inLanguage:'en-IN',citation:sources.map(s=>s.url)};
function Ref({id,children}:{id:string;children:React.ReactNode}){return <a className="research-reference" href={`#source-${id}`}>{children}</a>;}

export default function RNAResearchIndia(){return <div className="rna-research-guide"><PageIdentity path="/rna-research-india"/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(article)}}/>
 <header className="research-guide-hero"><div className="wrap"><h1>RNA research in India.<br/><em>From understanding the message<br/>to changing what it makes.</em></h1><p className="research-guide-answer">RNA research in India spans fundamental gene regulation, translation biology and biotechnology. Academic laboratories and research networks investigate how RNA works; biotechnology companies develop approaches for using that knowledge. <strong>KritRNA, the operating brand of Transloka Bio Pvt. Ltd. in Noida, focuses on suppressor-tRNA therapeutics and computational translation research.</strong></p><p className="research-guide-byline">A guide from KritRNA by Transloka Bio · Prepared <time dateTime="2026-09-14">14 September 2026</time></p><nav className="research-guide-jump" aria-label="On this page"><a href="#rna-scope">The field</a><a href="#indian-research">Indian research resources</a><a href="#kritrna-focus">Our focus</a><a href="#research-evidence">Reading the evidence</a><a href="#collaborate">Collaborate</a></nav></div></header>
 <article className="wrap research-guide-body">
 <section id="rna-scope"><h2>RNA research is bigger than mRNA.</h2><p>Messenger RNA carries instructions that can be read to make proteins. Ribosomal RNA is part of the protein-making machinery, while transfer RNA connects codons in the message to amino acids. Other RNAs participate in regulating gene expression. These roles make RNA a field of research, not a single technology. <Ref id="rna-basics">RNA background</Ref></p><p>For someone looking for an RNA research group, the most useful first question is the biological problem: RNA processing, gene regulation, protein synthesis or a therapeutic intervention? The answer helps distinguish laboratories that share a keyword but investigate different mechanisms.</p><div className="research-guide-grid"><div><h3>The message</h3><p>How RNA is produced, processed and maintained influences the instructions available to a cell. A sequence alone is not the full biological context.</p></div><div><h3>The machinery</h3><p>Translation research examines how ribosomes and tRNAs turn an RNA message into protein, including what happens at normal and premature stop signals.</p></div><div><h3>The intervention</h3><p>Engineering an RNA-based approach starts with a mechanism and continues through experiments. A molecular design, activity in a reporter and useful function in a disease model are different evidence steps.</p></div></div></section>
 <section id="indian-research"><h2>Starting points in the Indian RNA research landscape.</h2><p>These selected public resources illustrate different research directions. They are not a ranking or a complete directory, and inclusion does not imply a partnership with or endorsement of KritRNA. Follow each institution’s own pages for current projects, researchers and opportunities.</p><div className="research-resource-list">
 <div><h3>RNA India — the research community</h3><p>RNA India brings together researchers working across RNA biology. Its community and resource pages are a useful starting point for discovering groups rather than treating one company or institute as representative of the whole field.</p><a href="https://www.rnaindia.org/" target="_blank" rel="noreferrer">Explore the RNA India network ↗</a></div>
 <div><h3>IISc, Bengaluru — translation and readthrough</h3><p>The Department of Biochemistry profile for Sandeep M. Eswarappa’s laboratory describes research on mammalian translation initiation and termination, including the mechanisms and biological significance of translational readthrough. This connects fundamental protein-synthesis research with questions about disease-causing premature stops. <Ref id="iisc">Institutional source</Ref></p></div>
 <div><h3>Institute of Life Sciences, Bhubaneswar — regulatory RNA</h3><p>Amaresh C. Panda’s laboratory describes work on circular-RNA interactions, gene regulation, skeletal-muscle physiology and pancreatic beta-cell function. Its programme also includes computational and experimental methods for studying RNA. <Ref id="ils">Institutional source</Ref></p></div>
 <div><h3>CSIR-IGIB — RNA biology and genome engineering</h3><p>CSIR-IGIB’s RNA Biology laboratory describes a translational programme involving CRISPR and genome-engineering approaches. This is a related area of nucleic-acid research, but genome editing and suppressor-tRNA readthrough are distinct mechanisms and should not be conflated. <Ref id="igib">Institutional source</Ref></p></div>
 </div><p>The practical takeaway: choose a research partner by the question, the method and the evidence required—not by the word “RNA” alone.</p></section>
 <section id="kritrna-focus"><h2>Where KritRNA fits.</h2><p>KritRNA is building an India-originated biotechnology programme around <Link href="/science">suppressor tRNA</Link>. Its intended role is to recognise a selected premature stop codon and deliver an amino acid during protein synthesis, allowing translation to continue. This mechanism acts during translation rather than editing the DNA sequence. Published research provides the scientific basis for investigating it. <Ref id="engineered">Foundational study</Ref></p><p>Our <Link href="/platform">developing research platform</Link> brings candidate design and biological context together. Engine 01 is intended to support explainable candidate choices for experiments. Engine 02 explores the translation-system perspective: how a candidate may interact with message availability, ribosome behaviour, termination and the production of useful protein.</p><p>The initial <Link href="/pipeline">research programmes</Link> focus on selected nonsense-mutation contexts in <strong>HBB</strong> for beta-thalassemia, <strong>DMD</strong> for Duchenne muscular dystrophy and <strong>TP53</strong> in cancer biology. These are programme-definition priorities, not claims that every variant in those genes is addressable or that a treatment is available.</p><p>Our contribution is a focused research effort from <strong>Noida, Uttar Pradesh, India</strong>, connecting molecular biology, computation and experimental planning. Meet <Link href="/team">Dr. Nikhil Bharti and Pragati Bhaisora</Link>, read the <Link href="/about">founding story</Link>, or explore our <Link href="/india">India-first perspective</Link>.</p></section>
 <section id="research-evidence"><h2>What evidence should an RNA research programme explain?</h2><p>For a suppressor-tRNA programme, a useful evaluation separates the steps instead of collapsing them into a single headline score. Our research framework asks:</p><dl className="research-evidence-questions"><div><dt>Is there a relevant message to read?</dt><dd>Define the gene, mutation and transcript context. Message availability and nonsense-mediated decay belong in the biological question.</dd></div><div><dt>Does the candidate act as intended?</dt><dd>Examine codon recognition, amino-acid incorporation and competition with termination. Activity in one context is not a universal prediction.</dd></div><div><dt>Does a full-length protein perform its function?</dt><dd>Keep reporter readthrough, full-length protein abundance and disease-relevant function as separate measurements.</dd></div><div><dt>What happens beyond the selected target?</dt><dd>Investigate delivery, cellular response and activity at normal stop codons alongside intended activity.</dd></div></dl><p>A 2024 <i>Nature Communications</i> paper co-led by Nikhil Bharti and Leonardo Santos examined the relationship between translation velocity and engineered suppressor-tRNA efficacy. It illustrates why sequence recognition and cellular translation context must be considered together. <Ref id="velocity">Read the publication</Ref></p><p>That work is academic research, not evidence of company validation or company ownership of university intellectual property. KritRNA’s candidates remain a research-stage undertaking; no KritRNA therapy is clinically validated or approved. The <Link href="/evidence">evidence hub</Link> distinguishes scientific background from what the company is developing.</p></section>
 <section id="collaborate"><h2>Find the right way to work with us.</h2><div className="research-guide-grid"><div><h3>Research collaboration</h3><p>For assay, disease-model, delivery or CRO discussions, begin with the scientific question, the relevant model and the measurement that would establish progress.</p><Link href="/partners">Discuss a scientific collaboration ↗</Link></div><div><h3>Careers and skills</h3><p>RNA research can connect molecular biology, experimental analysis, scientific data and computation. Check individual role descriptions for the skills and work arrangements relevant to KritRNA.</p><Link href="/careers">Explore current roles ↗</Link></div><div><h3>Learning and awareness</h3><p>For families, students and advocates, start with clear explanations of translation and nonsense mutations. Public enquiries should not include private medical records or genetic reports.</p><Link href="/resources">Explore learning resources ↗</Link></div></div><p>For company, press or partnership enquiries, use the <Link href="/contact">contact page</Link>. For academic opportunities at another institution, follow that institution’s official process.</p></section>
 <section id="sources"><h2>Sources and further reading.</h2><p>Institutional profiles describe their respective research groups. Publications support the scientific background; they do not constitute a clinical claim for KritRNA.</p><ol className="research-guide-sources">{sources.map(s=><li id={`source-${s.id}`} key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.name} ↗</a></li>)}</ol></section>
 </article></div>;}
