import type {Metadata} from 'next';
import Link from 'next/link';
import Reveal from '@/components/Reveal';
import TranslationStory from '@/components/TranslationStory';
import {DEPENDENCIES,PUBLIC_RESEARCH} from '@/lib/publicStory';
export const metadata:Metadata={title:'Our Science',description:'How tRNA connects the genetic message to protein, what premature stops disrupt, and how suppressor tRNA may help translation continue.'};
const rationale=[['Works during translation','A suppressor tRNA acts while the ribosome reads mRNA. The intended mechanism does not edit the DNA sequence. Delivery and expression format determine how long the intervention persists.'],['Uses the cell’s message','The aim is to recover protein production from a transcript made by the cell. There must be enough relevant transcript available for that strategy to work.'],['Starts with a specific biological context','Codon recognition, amino-acid identity, tRNA function and the environment around the premature stop all matter. A candidate must be tested in a relevant system.'],['Builds transferable knowledge','Different genes can share a premature-stop mechanism. Evidence and methods may inform additional programmes, while disease biology, delivery and safety still require programme-specific work.']];
export default function Science(){return <div className="noir-system-page"><section className="page-hero"><div className="wrap"><Reveal><div className="eyebrow">THE SCIENCE OF CONTINUATION</div><h1 className="h1">From genetic instruction<br/><em>to working protein.</em></h1><p className="lead">DNA stores the instructions for making proteins. An mRNA working copy is read by the ribosome in three-letter codons. tRNAs connect those codons to amino acids, allowing a protein chain to grow. At the normal end of the message, release factors recognise a stop signal.</p></Reveal></div></section>
 <section><div className="wrap"><Reveal><div className="sec-head"><span className="micro">THE MOLECULAR ADAPTOR</span><h2 className="h2">One RNA strand. A highly organised fold.</h2><p>A tRNA is a single RNA molecule with intramolecularly paired stems and connecting loops. Its folded structure brings an amino-acid-carrying end and a codon-recognising region into the geometry needed for translation. It is not a DNA double helix.</p></div></Reveal><TranslationStory/></div></section>
 <section className="ink-sec"><div className="wrap"><Reveal><div className="sec-head"><div className="eyebrow">ONE MUTATION. TWO CONNECTED FAILURES.</div><h2 className="h2">The protein can be cut short. The message can also be lost.</h2><p>A nonsense mutation creates an early UAA, UAG or UGA stop. Premature termination can reduce useful protein output. Nonsense-mediated decay can additionally reduce the transcript, although the extent depends on sequence, transcript structure and cellular context.</p></div></Reveal><div className="failure-pair"><Reveal><article><span className="micro">PROTEIN CONSEQUENCE</span><h3>Full length is a starting point.</h3><p>The therapeutic goal is useful protein function, not simply a longer chain. Correct amino-acid incorporation, expression level, stability and activity need to be assessed.</p></article></Reveal><Reveal><article><span className="micro">TRANSCRIPT CONSEQUENCE</span><h3>There must be a message to read.</h3><p>Message availability and readthrough need to be considered together. A candidate’s success in one transcript or cell context does not establish its performance in another.</p></article></Reveal></div></div></section>
 <section><div className="wrap"><Reveal><div className="sec-head"><div className="eyebrow">THE SUPPRESSOR-tRNA IDEA</div><h2 className="h2">Read the premature stop as an opportunity to continue.</h2><p>An engineered suppressor tRNA can recognise a selected stop codon and deliver an amino acid. If it competes successfully with termination, translation can continue downstream towards a full-length protein. This is a therapeutic possibility that must be tested for activity, specificity and function.</p></div></Reveal><div className="standard-grid">{rationale.map(([t,p])=><Reveal key={t}><article><h3>{t}</h3><p>{p}</p></article></Reveal>)}</div></div></section>
 <section><div className="wrap"><Reveal><div className="sec-head"><div className="eyebrow">FOUR CONDITIONS, CONSIDERED TOGETHER</div><h2 className="h2">A successful design has to work inside biology.</h2></div></Reveal><div className="system-layer-list">{DEPENDENCIES.map(([n,t,q,p])=><Reveal key={n}><article><span className="micro">{n} / {t}</span><h3>{q}</h3><p>{p}</p></article></Reveal>)}</div><div className="safety-band"><span className="micro">NORMAL-STOP FIDELITY</span><p>Premature and native stops use the same stop-codon vocabulary. Selectivity cannot be assumed from the word “premature”. Normal-stop readthrough and broader cellular effects require measurement alongside target activity.</p></div></div></section>
 <section className="ink-sec"><div className="wrap"><div className="sec-head"><div className="eyebrow">PUBLIC SCIENTIFIC FOUNDATION</div><h2 className="h2">Research you can examine.</h2></div><div className="standard-grid"><Reveal><article><span className="micro">TRANSLATION CONTEXT</span><h3>{PUBLIC_RESEARCH.title}</h3><p>{PUBLIC_RESEARCH.venue}. {PUBLIC_RESEARCH.note}</p><a href={PUBLIC_RESEARCH.href} target="_blank" rel="noreferrer" className="underline-link">Read the paper ↗</a></article></Reveal><Reveal><article><span className="micro">STRUCTURAL REFERENCE</span><h3>A single-chain tRNA structure.</h3><p>The hero uses a rendering of the public 1EHZ yeast phenylalanine tRNA structure when reference data are available. It is a reference molecule, not a KritRNA therapeutic candidate.</p><a href="https://www.rcsb.org/structure/1EHZ" target="_blank" rel="noreferrer" className="underline-link">Examine the reference ↗</a></article></Reveal></div><div className="science-sources">Programme gene records: <a href="https://www.ncbi.nlm.nih.gov/gene/3043" target="_blank" rel="noreferrer">HBB ↗</a><a href="https://www.ncbi.nlm.nih.gov/gene/1756" target="_blank" rel="noreferrer">DMD ↗</a><a href="https://www.ncbi.nlm.nih.gov/gene/7157" target="_blank" rel="noreferrer">TP53 ↗</a></div></div></section>
 <section className="page-bottom-cta"><div className="wrap"><Reveal><h2 className="display-heading smaller">The science shapes<br/><em>what we build.</em></h2><p>KritRNA is developing a connected candidate-design and translation-systems platform to turn these biological questions into informed experimental choices.</p><Link href="/platform" className="underline-link">Explore the platform ↗</Link></Reveal></div></section></div>;}
