'use client';
import {useRef,useState} from 'react';
import {SITE} from '@/lib/content';
export default function ContactPage(){
 const [busy,setBusy]=useState(false),[done,setDone]=useState(false),[err,setErr]=useState(''),form=useRef<HTMLFormElement>(null);
 async function submit(event:React.FormEvent){event.preventDefault();setErr('');if(!form.current)return;const body=Object.fromEntries(new FormData(form.current).entries());setBusy(true);try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(response.ok)setDone(true);else setErr(data.error||'The message could not be sent. Please try again.');}catch{setErr('Network error. Please try again.');}finally{setBusy(false);}}
 const direct=[['General enquiries',SITE.email,`mailto:${SITE.email}`],['Careers',SITE.careersEmail,`mailto:${SITE.careersEmail}`],['Phone',SITE.phone,`tel:${SITE.phone.replace(/\s/g,'')}`],['Entity',SITE.legal,''],['CIN',SITE.cin,''],['Location',SITE.location,'']];
 return <section className="page-hero"><div className="wrap contact-wrap"><div className="eyebrow">CONTACT KRITRNA</div><h1 className="h1">Let’s build<br/><em>a conversation.</em></h1><p className="lead">Partnerships, investment, scientific collaboration, press, careers or a question about the science—use the relevant address below.</p><div className="contact-layout"><div className="direct-contact"><h2>Direct enquiries</h2>{direct.map(([label,value,href])=><div key={label}><span>{label}</span>{href?<a href={href}>{value}</a>:<p>{value}</p>}</div>)}</div>{done?<div className="contact-form" role="status"><h2>Message sent.</h2><p>Thank you for contacting KritRNA. Your enquiry has been submitted.</p></div>:<form ref={form} onSubmit={submit} className="contact-form" aria-label="Contact enquiry"><div className="field"><label htmlFor="contact-name">Name *</label><input id="contact-name" name="name" autoComplete="name" required placeholder="Your name"/></div><div className="contact-fields"><div className="field"><label htmlFor="contact-email">Email *</label><input id="contact-email" name="email" type="email" autoComplete="email" required placeholder="you@email.com"/></div><div className="field"><label htmlFor="contact-organization">Organisation</label><input id="contact-organization" name="organization" autoComplete="organization" placeholder="Company / institution"/></div></div><div className="field"><label htmlFor="contact-message">Message *</label><textarea id="contact-message" name="message" required placeholder="How can we help?" aria-describedby="contact-privacy"/></div><p className="privacy-note" id="contact-privacy">For professional and general enquiries. Please do not submit medical records, genetic reports or patient health information.</p><input name="website" tabIndex={-1} autoComplete="off" className="hp" aria-hidden/>{err&&<p className="form-error" role="alert">{err}</p>}<button className="btn btn-solid" type="submit" disabled={busy}>{busy?'Sending…':'Send message ↗'}</button></form>}</div></div><style jsx>{`
 .contact-wrap{max-width:1100px}.h1{margin-top:25px}.lead{margin-top:24px}.contact-layout{display:grid;grid-template-columns:minmax(0,.85fr) minmax(0,1.3fr);gap:55px;margin-top:50px;align-items:start}.direct-contact,.contact-form{min-width:0}.direct-contact h2,.contact-form h2{font-size:2rem;margin-bottom:23px}.direct-contact>div{border-top:1px solid var(--rule);padding:17px 0}.direct-contact span{display:block;font-family:var(--mono);font-size:.6rem;text-transform:uppercase;letter-spacing:.09em;color:var(--ink-mute);margin-bottom:7px}.direct-contact a,.direct-contact p{font-size:.88rem;line-height:1.8;overflow-wrap:anywhere}.direct-contact a{color:var(--gold)}.contact-form{border:1px solid var(--rule);border-radius:4px;padding:28px;background:var(--paper)}.contact-fields{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px}.contact-form input,.contact-form textarea{min-width:0;max-width:100%}.contact-form button{width:100%;justify-content:center}.privacy-note{font-size:.71rem;line-height:1.8;color:var(--ink-soft);margin:0 0 22px}@media(max-width:750px){.contact-layout{grid-template-columns:minmax(0,1fr);gap:35px}.contact-form{padding:22px}}@media(max-width:450px){.contact-fields{grid-template-columns:minmax(0,1fr);gap:0}.contact-form{padding:20px}}
 `}</style></section>;
}
