import type {Metadata} from 'next';
import Link from 'next/link';
import Reveal from '@/components/Reveal';
import {PROGRAMS} from '@/lib/content';
export const metadata:Metadata={title:'India-First',description:'Why KritRNA is being built from India: locally relevant rare-disease priorities, scientific capability, validation partnerships and an India-based company platform.'};
const PILLARS=[
 ['Disease relevance',`KritRNA begins with selected nonsense-mutation contexts in ${PROGRAMS.map(p=>p.gene).join(', ')}, including an India-priority focus on β-thalassemia.`],
 ['Scientific ownership','The computational platform, candidate logic and future experimental evidence are being organised as company-owned capability developed from India.'],
 ['Validation network','The development path depends on Indian CROs, research laboratories, clinicians, hospitals and rare-disease communities working through formal collaborations.'],
 ['Access-aware development','Early decisions about indication, assay, delivery and evidence should reflect the realities of patients, healthcare systems and research infrastructure in India.']
];
const PATH=[['01','Define locally relevant mutation contexts','Select disease and variant contexts where the biology, unmet need and experimental path can be defended.'],['02','Design candidates computationally','Generate and rank suppressor-tRNA candidates using the KritRNA platform and documented biological constraints.'],['03','Validate through formal collaborations','Test selected candidates through appropriate research laboratories, CROs and disease-relevant experimental systems.'],['04','Build evidence before expansion','Advance only when reproducible molecular, protein-restoration and safety evidence supports the next step.']];
export default function IndiaPage(){return <>
 <section className="page-hero"><div className="wrap"><Reveal><div className="eyebrow">India-first</div><h1 className="h1" style={{marginTop:24}}>Built in India.<br/><em>Designed for global science.</em></h1><p className="lead" style={{marginTop:28}}>KritRNA is being developed by Transloka Bio Pvt. Ltd. in Noida as an India-first suppressor-tRNA platform. India-first does not mean India-only: it means building scientific ownership, evidence generation and disease priorities from India while meeting globally credible standards.</p></Reveal></div></section>
 <section className="ink-sec"><div className="wrap"><Reveal><div className="sec-head"><div className="eyebrow">The India-first proposition</div><h2 className="h2">Start where the need, science and execution can meet.</h2><p>The proposition is to build a defensible biotechnology platform, validation network and future development pathway from the Indian research ecosystem.</p></div></Reveal><div className="grid cols-4">{PILLARS.map(([title,text])=><Reveal key={title}><article className="cell" style={{height:'100%'}}><h3>{title}</h3><p>{text}</p></article></Reveal>)}</div></div></section>
 <section><div className="wrap split-2"><Reveal><div className="eyebrow">Initial focus</div><h2 className="h2" style={{marginTop:16}}>Three programmes with different biological and access questions.</h2><p className="lead" style={{marginTop:22}}>{PROGRAMS.map(p=>p.gene).join(', ')} provide distinct tests of the same platform thesis. Each programme requires its own mutation context, amino-acid restoration logic, assay system, delivery strategy and safety evidence.</p><div className="callout">These are early research programmes. KritRNA does not currently offer a treatment, clinical trial or patient-enrolment pathway.</div><details className="landscape-notes"><summary>Broader scientific context: CFTR / cystic fibrosis <span aria-hidden="true">+</span></summary><p style={{paddingBottom:22,color:'var(--ink-soft)',fontSize:'.9rem'}}>Pulmonary and epithelial nonsense-mutation contexts were included in the earlier India-page research landscape. This material is retained as broader scientific context; the shared programme list reflects the website’s current HBB, DMD and TP53 priorities.</p></details></Reveal><div>{PROGRAMS.map((p,i)=><Reveal key={p.gene}><article className="cell" style={{borderTop:'1px solid var(--rule)'}}><div className="micro accent-text">0{i+1} / {p.gene}</div><h3 style={{marginTop:12}}>{p.name}</h3><p>{p.goal}</p><p style={{marginTop:12,fontSize:'.78rem'}}>{p.stage} · Next: {p.next}</p></article></Reveal>)}</div></div></section>
 <section><div className="wrap"><Reveal><div className="sec-head"><div className="eyebrow">Execution pathway</div><h2 className="h2">Evidence before expansion.</h2><p>The India-first strategy is organised around an evidence sequence rather than broad claims of platform readiness.</p></div></Reveal><div className="grid cols-2">{PATH.map(([n,title,text])=><Reveal key={n}><article className="cell" style={{height:'100%'}}><div className="micro accent-text">{n}</div><h3 style={{marginTop:14}}>{title}</h3><p>{text}</p></article></Reveal>)}</div></div></section>
 <section className="ink-sec center"><div className="wrap"><Reveal><h2 className="h2">India-first scientific infrastructure requires collaborators.</h2><p className="lead" style={{margin:'20px auto 0'}}>KritRNA is open to structured discussions with research laboratories, CROs, clinicians, hospitals, incubators, grant programmes, patient organisations and aligned investors.</p><div style={{marginTop:28,display:'flex',justifyContent:'center',gap:15,flexWrap:'wrap'}}><Link className="editorial-button light-button" href="/contact">Discuss an India collaboration ↗</Link><Link className="text-link" href="/pipeline">View the research programmes ↗</Link></div></Reveal></div></section>
 </>;}
