import Link from 'next/link';
import Image from 'next/image';
import Reveal from '@/components/Reveal';
import MolecularHero from '@/components/MolecularHero';
import TranslationStory from '@/components/TranslationStory';
import {PROGRAMS,TEAM} from '@/lib/content';

const AUDIENCES=[
  ['Families & advocates','Understand how premature stop codons interrupt protein production and why suppressor tRNA offers a new route toward restoration.','/resources','Explore the science in plain language'],
  ['Scientists & development partners','Examine the molecular logic, dual-engine architecture, experimental strategy and collaboration opportunities behind the platform.','/platform','Enter the platform'],
  ['Investors & strategic partners','Review the shared-mechanism thesis, development strategy, programme logic and India-built biotechnology opportunity.','/investors','View the investment thesis'],
  ['Builders of the company','Join a founding-stage team working across computation, molecular biology, operations and scientific communication.','/careers','Explore open roles'],
];
const GATES=[['01','Charging','The right amino-acid identity.'],['02','Transcript context','The right message and molecular setting.'],['03','Delivery','The right tissue and cellular destination.'],['04','Native-stop safety','The right balance of activity and specificity.']];
function Arrow(){return <span aria-hidden="true">↗</span>;}
function Network(){
  const pts=Array.from({length:12},(_,i)=>({x:220+Math.cos(i*Math.PI/6)*155,y:160+Math.sin(i*Math.PI/6)*112}));
  return <svg className="engine-network" viewBox="0 0 440 320" aria-hidden="true"><ellipse cx="220" cy="160" rx="156" ry="112" fill="none" stroke="currentColor" opacity=".13"/>{pts.map((p,i)=><g key={i}><path d={`M${p.x},${p.y} Q220,160 ${pts[(i+5)%12].x},${pts[(i+5)%12].y}`} fill="none" stroke="currentColor" opacity=".14"/><circle cx={p.x} cy={p.y} r={i%3===0?7:4} fill="currentColor" className="network-node" style={{animationDelay:`${i*.2}s`}}/></g>)}<circle cx="220" cy="160" r="42" fill="none" stroke="currentColor" opacity=".3"/><text x="220" y="164" textAnchor="middle" fill="currentColor" fontSize="12" fontFamily="monospace">TRANSLATION</text></svg>;
}
export default function Home(){return <div className="editorial-home">
  <header className="editorial-hero">
    <div className="hero-grain" aria-hidden="true"/>
    <div className="wrap hero-composition">
      <div className="hero-copy"><div className="hero-kicker"><span/>INDIA-BUILT PRECISION TRANSLATION THERAPEUTICS</div>
        <h1>Reading through<br/><em>silence.</em></h1>
        <p className="hero-promise">Restoring the protein.</p>
        <p className="hero-description">A new possibility for genetic diseases.<br/>Engineered at the level of translation.</p>
        <div className="hero-actions"><Link className="editorial-button light-button" href="/science">Explore our science <Arrow/></Link><Link className="text-link" href="/partners">Build with us <Arrow/></Link></div>
      </div>
      <MolecularHero/>
    </div>
    <div className="wrap hero-baseline"><a href="#the-possibility" className="scroll-cue"><span aria-hidden="true">↓</span> SCROLL TO DISCOVER</a><span>MOLECULAR BIOLOGY <i/> COMPUTATIONAL INTELLIGENCE <i/> HUMAN POSSIBILITY</span><span className="hero-edition">KRITRNA / 01</span></div>
  </header>
  <section id="the-possibility" className="manifesto-section"><div className="wrap">
    <div className="section-index"><span>01 / THE POSSIBILITY</span><span>SMALL MOLECULE. PROFOUND PURPOSE.</span></div>
    <div className="manifesto-layout"><Reveal><h2 className="display-heading">The message<br/>is interrupted.<br/><em>The possibility<br/>is not.</em></h2></Reveal><div className="manifesto-copy"><Reveal><span className="micro accent-text">ENGINEERING THE LANGUAGE OF LIFE</span><p className="large-body">KritRNA is building a suppressor tRNA therapeutics platform for rare genetic diseases caused by premature stop codons.</p><p>We combine molecular biology, evidence-led programme selection and computational translation science to identify where restoring full-length protein can create the strongest therapeutic opportunity.</p><Link href="/problem" className="underline-link">Understand the molecular challenge <Arrow/></Link></Reveal><div className="mission-footnote"><span className="status-dot"/> DISCOVERY-LED. EVIDENCE-GUIDED. INDIA-BUILT.</div></div></div>
  </div></section>
  <section className="mechanism-section" id="mechanism"><div className="wrap">
    <div className="section-index"><span>02 / THE SCIENCE</span><Link href="/science">FOLLOW THE MOLECULAR LOGIC ↗</Link></div>
    <div className="mechanism-layout"><div className="mechanism-copy"><Reveal><span className="micro accent-text">THE MOLECULAR PROBLEM</span><h2 className="display-heading smaller">A stop too early.<br/><em>A way to continue.</em></h2><p>A nonsense mutation inserts an early stop signal into a protein-coding message. The ribosome leaves before the protein is complete, often reducing or eliminating a protein the cell needs.</p></Reveal><Reveal><h3>Reprogramme translation to continue.</h3><p>Engineered suppressor tRNAs can recognise selected premature stop codons and deliver an amino acid, allowing the ribosome to continue toward a full-length protein. KritRNA is building the design and evidence system required to make that possibility precise, programmable and disease-relevant.</p></Reveal></div><Reveal><TranslationStory/></Reveal></div>
  </div></section>
  <section className="platform-section" id="engines"><div className="wrap">
    <div className="section-index"><span>03 / THE PLATFORM</span><span>TWO ENGINES. ONE LEARNING LOOP.</span></div>
    <div className="platform-intro"><Reveal><h2 className="display-heading">Design the molecule.<br/><em>Understand the system.</em></h2></Reveal><Reveal><p className="large-body">Biology does not work in isolation.<br/>Neither should therapeutic design.</p><p>KritRNA is developing two connected engines that transform a target nonsense mutation into a biologically constrained, experimentally testable suppressor tRNA shortlist.</p></Reveal></div>
    <div className="engine-spread"><Reveal><article className="engine-panel engine-one"><div className="engine-top"><span className="micro">SUPPRESSOR-tRNA DESIGN</span><span className="engine-number">01</span></div><div className="sequence-art" aria-hidden="true"><div>A U G C A G U C</div><div>G C <span>U G A</span> A G</div><div>U A G C U A G C</div><div className="sequence-selection">CONTEXT → CANDIDATE</div></div><h3>Candidate generation<br/>and ranking.</h3><p>Sequence design, processing and identity constraints, structure and thermodynamics, kinetic context, normal-stop risk, explainable scoring and Pareto selection.</p><Link className="underline-link" href="/platform">Explore Engine 01 <Arrow/></Link></article></Reveal><Reveal delay={.08}><article className="engine-panel engine-two"><div className="engine-top"><span className="micro">TRANSLATION SMALL-WORLD</span><span className="engine-number">02</span></div><Network/><h3>System-level<br/>consequence modelling.</h3><p>A mechanistic network connecting initiation, elongation, termination, ribosome traffic, NMD, rescue, stress signalling, folding and protein output.</p><Link className="underline-link" href="/small-world">Explore Engine 02 <Arrow/></Link></article></Reveal></div>
    <div className="engine-loop"><span>DESIGN</span><i>→</i><span>TEST</span><i>→</i><span>LEARN</span><i>↺</i><p>Two connected engines under development, designed to support an experimental design–test–learn loop.</p></div>
    <div className="gate-strip">{GATES.map(([n,title,text])=><Reveal key={n}><div><span className="micro">{n} / QUALITY GATE</span><h3>{title}</h3><p>{text}</p></div></Reveal>)}</div>
  </div></section>
  <section className="programmes-section" id="programmes"><div className="wrap">
    <div className="section-index"><span>04 / RESEARCH PROGRAMMES</span><span>EARLY RESEARCH · PROGRAMME DEFINITION</span></div>
    <div className="programmes-intro"><Reveal><h2 className="display-heading">One programmable modality.<br/><em>Distinct biological questions.</em></h2></Reveal><Reveal><p>Our first programmes test the platform across hematology, neuromuscular disease and oncology. Each starts with a defined mutation context and an evidence-gated development path.</p></Reveal></div>
    <div className="programme-list">{PROGRAMS.map((p,i)=><Reveal key={p.gene}><details className="programme-row" open={i===0}><summary><span className="programme-count">0{i+1}</span><span className="programme-title"><span className="micro">{p.area}</span><span>{p.name}</span></span><span className="gene-tag">{p.gene}</span><span className="programme-expand" aria-hidden="true">+</span></summary><div className="programme-detail"><p>{p.goal}</p><div><span className="micro">CURRENT MILESTONE</span><p>{p.stage}</p></div><div><span className="micro">NEXT EVIDENCE GATE</span><p>{p.next}</p></div></div></details></Reveal>)}</div>
    <Link href="/pipeline" className="underline-link">Explore the research programmes <Arrow/></Link>
  </div></section>
  <section className="india-editorial" id="india"><div className="wrap">
    <div className="section-index"><span>05 / OUR ORIGIN. OUR AMBITION.</span><span>INDIA → THE WORLD</span></div>
    <div className="india-composition"><Reveal><div className="origin-symbol" aria-hidden="true">कृ<span>kṛ / TO MAKE. TO CREATE. TO ACT.</span><div className="origin-ring"/></div></Reveal><div><Reveal><span className="micro">INDIA-FIRST BIOTECHNOLOGY</span><h2 className="display-heading">Rooted in India.<br/><em>Built for possibility.</em></h2><p className="large-body">Built in India. Designed for global science.</p><p>KritRNA is creating India-owned capability in suppressor tRNA therapeutics, computational translation biology and evidence-driven drug discovery—while building to global scientific and regulatory standards.</p></Reveal><div className="india-principles">{['Scientific ownership from India','β-thalassemia as an India-priority programme','Evidence generated through formal collaborations','Global scientific and regulatory standards'].map(t=><div key={t}><span aria-hidden="true">↗</span>{t}</div>)}</div><Link href="/india" className="underline-link">The India-first strategy <Arrow/></Link></div></div>
  </div></section>
  <section className="people-section"><div className="wrap">
    <div className="section-index"><span>06 / THE PEOPLE BEHIND THE PURPOSE</span><Link href="/team">MEET THE TEAM ↗</Link></div>
    <div className="people-layout"><Reveal><div className="people-copy"><h2 className="display-heading smaller">Serious science.<br/><em>Shared purpose.</em></h2><p>KritRNA connects molecular science, therapeutic design, company building and patient-centred communication within one focused platform.</p><Link href="/team" className="underline-link">Our founders and scientific network <Arrow/></Link></div></Reveal><div className="founder-pair">{[TEAM.lead,TEAM.outreach].map(p=><Reveal key={p.name}><Link href="/team" className="founder-card"><div className="founder-photo"><Image src={p.photo} alt={p.name} width={420} height={500} sizes="(max-width: 640px) 44vw, 280px"/></div><h3>{p.name}</h3><p>{p.role}</p></Link></Reveal>)}</div></div>
  </div></section>
  <section className="evidence-editorial"><div className="wrap"><div className="section-index"><span>07 / THE EVIDENCE</span><Link href="/evidence">EXPLORE THE EVIDENCE HUB ↗</Link></div><div className="evidence-layout"><Reveal><h2 className="display-heading smaller">Ambition, grounded<br/><em>in the evidence.</em></h2><p>The field has moved from possibility to disciplined execution.</p></Reveal><Reveal><p className="large-body">The differentiator is how candidate design, disease context, delivery and safety come together.</p><p>Suppressor tRNA has reached a new stage of external validation. The differentiator now is not whether readthrough can occur, but whether candidate design, disease context, delivery and safety are integrated with enough discipline to produce durable programmes.</p><Link href="/evidence" className="underline-link">How evidence becomes a decision <Arrow/></Link></Reveal></div><details className="landscape-notes"><summary>Explore the existing stop-gain landscape and our decision framework <span aria-hidden="true">+</span></summary><div className="landscape-grid"><div><strong>92,157</strong><p>Distinct stop-gain variants catalogued across ClinVar.</p><small>A measurable molecular landscape for programme discovery.</small></div><div><strong>7,811</strong><p>Genes represented in the stop-gain landscape.</p><small>A platform opportunity extending across many disease areas.</small></div><div><strong>4 gates</strong><p>Charging, transcript context, delivery and native-stop safety.</p><small>The operating framework guiding candidate quality.</small></div><div><strong>India-first</strong><p>Population-aware evidence and development strategy.</p><small>Domestic origination capability built for global standards.</small></div></div><p className="landscape-caption">Catalogue figures retained from KritRNA’s existing landscape presentation; not live database totals, patient counts or a measure of therapeutic eligibility. <Link href="/problem">Landscape context ↗</Link></p></details></div></section>
  <section className="audience-section"><div className="wrap"><div className="section-index"><span>08 / FIND YOUR WAY IN</span><span>DIFFERENT PERSPECTIVES. ONE SCIENTIFIC MISSION.</span></div><div className="audience-list">{AUDIENCES.map(([title,text,href,action],i)=><Reveal key={title}><Link className="audience-row" href={href}><span className="micro">0{i+1}</span><div><h3>{title}</h3><p>{text}</p><span className="audience-action">{action}</span></div><span className="audience-arrow" aria-hidden="true">↗</span></Link></Reveal>)}</div></div></section>
  <section className="closing-section"><div className="closing-orbit" aria-hidden="true"/><div className="wrap"><Reveal><div className="micro">THE MEANING OF KRITRNA</div><h2 className="display-heading">Created with purpose.<br/><em>Engineered to continue.</em></h2><p>KritRNA draws its name from कृ (<em>kṛ</em>), the Sanskrit root meaning “to make, create or act,” and tRNA—the molecular adaptor that helps translate genetic information into protein. Together, the name means tRNA created with purpose: engineered to recognise selected premature stop codons and help translation continue toward a full-length protein.</p><div className="closing-actions"><Link className="editorial-button light-button" href="/partners">Scientific or CRO collaboration <Arrow/></Link><Link className="text-link" href="/investors">Investor discussion <Arrow/></Link><Link className="text-link" href="/careers">Join the team <Arrow/></Link></div></Reveal></div></section>
</div>;}
