import Link from 'next/link';
import TranslationTrack from '@/components/TranslationTrack';
import Reveal from '@/components/Reveal';
import { ConstellationWorld } from '@/components/ConceptWorlds';
import { PROGRAMS } from '@/lib/content';
const AUDIENCES=[['Families & advocates','Understand how premature stop codons interrupt protein production and why suppressor tRNA offers a new route toward restoration.','/resources','Explore the science in plain language'],['Scientists & development partners','Examine the molecular logic, dual-engine architecture, experimental strategy and collaboration opportunities behind the platform.','/platform','Enter the platform'],['Investors & strategic partners','Review the shared-mechanism thesis, development strategy, programme logic and India-built biotechnology opportunity.','/investors','View the investment thesis'],['Builders of the company','Join a founding-stage team working across computation, molecular biology, operations and scientific communication.','/careers','Explore open roles']];
const EVIDENCE=[['92,157','distinct stop-gain variants catalogued across ClinVar','A measurable molecular landscape for programme discovery'],['7,811','genes represented in the stop-gain landscape','A platform opportunity extending across many disease areas'],['4 gates','charging, transcript context, delivery and native-stop safety','The operating framework guiding candidate quality'],['India-first','population-aware evidence and development strategy','Domestic origination capability built for global standards']];
export default function Home(){return <div className="mockup-home">
<header className="approved-scene approved-hero"><img src="/approved-mockups/hero.webp" alt="KritRNA — Reading through silence, restoring the protein."/><nav className="scene-hotspots" aria-label="Homepage navigation"><Link className="hs science" href="/science">Science</Link><Link className="hs evidence" href="/evidence">Evidence</Link><Link className="hs approach" href="/platform">Approach</Link><Link className="hs about" href="/about">About</Link><Link className="hs careers" href="/careers">Careers</Link><Link className="hs contact" href="/contact">Contact</Link><Link className="hs hero-science" href="/science">Understand the science</Link><Link className="hs hero-evidence" href="/evidence">Explore the evidence</Link></nav></header>
<section className="evidence-section"><div className="wrap"><Reveal><div className="sec-head"><div className="eyebrow">A category becoming real</div><h2 className="h2">The field has moved from possibility to disciplined execution.</h2><p>Suppressor tRNA has reached a new stage of external validation. The differentiator now is not whether readthrough can occur, but whether candidate design, disease context, delivery and safety are integrated with enough discipline to produce durable programmes.</p></div></Reveal><div className="evidence-line">{EVIDENCE.map(([v,l,n],i)=><Reveal key={v} delay={i*.05}><article><b>{v}</b><h3>{l}</h3><p>{n}</p></article></Reveal>)}</div><Link className="text-link" href="/evidence">See how KritRNA turns evidence into decisions →</Link></div></section>
<section className="approved-scene approved-molecular"><img src="/approved-mockups/molecular.webp" alt="A molecular adaptor, redesigned with intent."/><Link className="hs molecular-cta" href="/science">Explore the detailed science</Link></section>
<section className="ink-sec translation-detail"><div className="wrap"><div className="translation-explainer"><div className="split-2"><Reveal><div><div className="eyebrow">The molecular problem</div><h3>The cell reaches “stop” too early</h3><p>A nonsense mutation inserts an early stop signal into a protein-coding message. The ribosome leaves before the protein is complete, often reducing or eliminating a protein the cell needs.</p></div></Reveal><Reveal delay={.08}><TranslationTrack/></Reveal></div><div className="split-2"><Reveal><div><div className="eyebrow">The KritRNA approach</div><h3>Reprogramme translation to continue</h3><p>Engineered suppressor tRNAs can recognise selected premature stop codons and deliver an amino acid, allowing the ribosome to continue toward a full-length protein. KritRNA is building the design and evidence system required to make that possibility precise, programmable and disease-relevant.</p></div></Reveal><Reveal delay={.08}><TranslationTrack readthrough/></Reveal></div></div></div></section>
<section className="approved-scene approved-platform"><img src="/approved-mockups/platform.webp" alt="From possibility to a testable shortlist."/><Link className="hs platform-cta" href="/platform">Explore the platform</Link></section>
<section className="ink-sec platform-detail"><div className="wrap"><Reveal><div className="sec-head"><div className="eyebrow">The dual-engine architecture</div><h2 className="h2">Design the molecule. Model the system.</h2><p>KritRNA is developing two connected engines that transform a target nonsense mutation into a biologically constrained, experimentally testable suppressor tRNA shortlist.</p></div></Reveal><div className="engine-notes"><article><span>Engine 01 · suppressor-tRNA design</span><h3>Candidate generation and ranking</h3><p>Sequence design, processing and identity constraints, structure and thermodynamics, kinetic context, normal-stop risk, explainable scoring and Pareto selection.</p></article><article><span>Engine 02 · translation small-world</span><h3>System-level consequence modelling</h3><p>A mechanistic network connecting initiation, elongation, termination, ribosome traffic, NMD, rescue, stress signalling, folding and protein output.</p></article></div><div className="actions"><Link className="btn btn-solid" href="/platform">See the dual-engine architecture →</Link><Link className="btn btn-ghost" href="/small-world">Explore the small-world engine</Link></div></div></section>
<section className="programmes-section"><div className="wrap programmes-content"><Reveal><div className="sec-head"><div className="eyebrow">Initial research focus</div><h2 className="h2">Three programmes. One programmable modality.</h2><p>Our first programmes test the platform across hematology, neuromuscular disease and oncology.</p></div></Reveal><div className="programme-gallery">{PROGRAMS.map((p,i)=><Reveal key={p.name} delay={i*.06}><article><span>{p.area}</span><h3>{p.name}</h3><p>{p.goal}</p><dl><dt>Current milestone</dt><dd>{p.stage}</dd><dt>Next</dt><dd>{p.next}</dd></dl></article></Reveal>)}</div><Link className="btn btn-ghost programme-cta" href="/pipeline">Explore the research programmes →</Link></div></section>
<section className="india-section ink-sec"><div className="wrap split-2"><Reveal><div><div className="eyebrow">India-first biotechnology</div><h2 className="h2">Built in India. Designed for global science.</h2><p className="lead">KritRNA is creating India-owned capability in suppressor tRNA therapeutics, computational translation biology and evidence-driven drug discovery—while building to global scientific and regulatory standards.</p><Link className="btn btn-ghost light" href="/india">See the India-first strategy →</Link></div></Reveal><ConstellationWorld/></div></section>
<section className="audience-section"><div className="wrap"><Reveal><div className="sec-head"><div className="eyebrow">Discover KritRNA</div><h2 className="h2">Different perspectives. One scientific mission.</h2><p>KritRNA connects molecular science, therapeutic design, company building and patient-centred communication within one focused platform.</p></div></Reveal><div className="audience-grid">{AUDIENCES.map(([t,x,h,a],i)=><Reveal key={t} delay={i*.04}><article><i>0{i+1}</i><h3>{t}</h3><p>{x}</p><Link href={h}>{a} →</Link></article></Reveal>)}</div></div></section>
<section className="meaning-section ink-sec"><div className="wrap center"><Reveal><div className="eyebrow centered">The meaning of KritRNA</div><h2 className="h1"><em>Created with purpose.</em><br/>Engineered to continue.</h2><p className="lead">KritRNA draws its name from कृ (<em>kṛ</em>), the Sanskrit root meaning “to make, create or act,” and tRNA—the molecular adaptor that helps translate genetic information into protein. Together, the name means tRNA created with purpose: engineered to recognise selected premature stop codons and help translation continue toward a full-length protein.</p></Reveal><div className="actions centered"><Link className="btn btn-solid ivory" href="/partners">Scientific or CRO collaboration</Link><Link className="btn btn-ghost light" href="/investors">Investor discussion</Link><Link className="btn btn-ghost light" href="/careers">Join the team</Link></div></div></section>
</div>}
