export const UPDATES = [
  { date: '2026-07-11', type: 'Website', title: 'Public scientific architecture expanded', summary: 'Science, India-first, investor and translation small-world pages now present KritRNA’s platform, evidence and development strategy.' },
  { date: '2026-07-11', type: 'Platform', title: 'Research programmes published', summary: 'HBB, DMD and TP53 programmes are shown through explicit development milestones.' },
  { date: '2026-07-11', type: 'Hiring', title: 'Founding roles and internships', summary: 'Current roles cover machine learning, research-data curation, operations and scientific communications.' },
];

export const SEARCH_INDEX = [
  { href:'/', title:'Home', section:'Overview', description:'KritRNA overview, suppressor tRNA solution, audience pathways, India-first strategy and current programmes.', keywords:'home company suppressor trna rare disease cancer' },
  { href:'/problem', title:'The shared molecular problem', section:'Science', description:'How premature stop codons interrupt protein production and why suppressor tRNA offers a distinct programmable solution.', keywords:'problem nonsense mutation gene therapy readthrough solution' },
  { href:'/science', title:'Suppressor tRNA science', section:'Science', description:'One molecular failure across many diseases and the promise of programmable suppressor tRNA therapeutics.', keywords:'science suppressor trna nmd aminoacylation promise' },
  { href:'/platform', title:'Dual-engine platform', section:'Technology', description:'Candidate design, translation-system modelling and the design-test-learn loop.', keywords:'platform ai engine machine learning' },
  { href:'/small-world', title:'Translation small-world engine', section:'Technology', description:'Ribosome traffic, collision, ISR, NMD and systems modelling.', keywords:'small world ribosome isr network' },
  { href:'/pipeline', title:'Research programmes', section:'Pipeline', description:'HBB, DMD and TP53 research programmes across hematology, neuromuscular disease and oncology.', keywords:'pipeline hbb dmd tp53 p53 cancer' },
  { href:'/india', title:'India-first strategy', section:'Company', description:'Rare-disease ecosystem, validation pathways and India-based scientific ownership.', keywords:'india policy centres excellence' },
  { href:'/partners', title:'Partner with KritRNA', section:'Connect', description:'Pathways for CROs, hospitals, laboratories, patient organisations, pharma and incubators.', keywords:'partner cro hospital patient organisation' },
  { href:'/community', title:'Community collaboration', section:'Connect', description:'Ethical collaboration pathway for rare-disease organisations and advocates.', keywords:'community patient organisation advocacy outreach' },
  { href:'/investors', title:'Investor overview', section:'Connect', description:'Platform thesis, milestones, capital strategy and controlled material requests.', keywords:'investor funding grant capital' },
  { href:'/impact', title:'Potential impact', section:'Company', description:'Cross-disease platform potential, India-owned capability and access-aware development.', keywords:'impact access India platform' },
  { href:'/about', title:'About Transloka Bio and KritRNA', section:'Company', description:'Legal entity, KritRNA name, mission and operating principles.', keywords:'about legal mission name meaning' },
  { href:'/how-we-work', title:'How we work at Transloka Bio', section:'Company', description:'Scientific standards, sustainable work, inclusion, confidentiality and founding-stage hiring principles.', keywords:'culture values inclusion work employment hiring' },
  { href:'/team', title:'Team', section:'Company', description:'Founders, computational build, advisory network and publication record.', keywords:'team founder Nikhil Pragati' },
  { href:'/updates', title:'Updates', section:'Company', description:'Verified company, science and hiring updates.', keywords:'updates news' },
  { href:'/careers', title:'Careers', section:'Connect', description:'Open roles, company culture and application pathway.', keywords:'career job internship culture' },
  { href:'/resources', title:'Public and family resources', section:'Learn', description:'Plain-language and bilingual starting points for genes, proteins, premature stops and suppressor tRNA science.', keywords:'patient family Hindi public guide' },
  { href:'/explorer', title:'Disease and gene explorer', section:'Learn', description:'Educational HBB, DMD and TP53 research contexts and validation questions.', keywords:'disease gene explorer stop codon cancer' },
  { href:'/glossary', title:'Scientific glossary', section:'Learn', description:'Definitions for PTC, NMD, aaRS, readthrough, translation and related terms.', keywords:'glossary definition terminology' },
  { href:'/references', title:'Scientific references', section:'Learn', description:'Persistent scientific, gene and policy sources used across the public website.', keywords:'references citations DOI PubMed policy' },
  { href:'/ask', title:'Ask KritRNA', section:'Assistant', description:'Full-page grounded assistant with suggested questions and safety boundaries.', keywords:'chatbot ask assistant' },
  { href:'/faq', title:'FAQ', section:'Help', description:'Answers about the company, science, stage and data handling.', keywords:'faq questions' },
  { href:'/privacy', title:'Privacy and data use', section:'Legal', description:'How website enquiry, recruitment, newsletter, analytics and assistant information is handled.', keywords:'privacy data consent retention rights' },
];
