'use client';
import { useState } from 'react';

type Source={id:string;title:string;href:string}; type Msg={role:'user'|'assistant';content:string;sources?:Source[]};
const SUGGESTIONS=['How does a suppressor tRNA work?','What must be solved before a candidate can advance?','Which research programmes is KritRNA pursuing?','How can a CRO or investor work with KritRNA?'];
export default function AskPageClient(){
 const [messages,setMessages]=useState<Msg[]>([{role:'assistant',content:'Ask about KritRNA, suppressor-tRNA science, the platform, programmes, team, careers or partnerships. I use approved public information only.'}]); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false);
 async function send(text=input){const question=text.trim(); if(!question||busy)return; const next=[...messages,{role:'user',content:question} as Msg]; setMessages(next);setInput('');setBusy(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next.slice(-6).map(({role,content})=>({role,content}))})});const data=await r.json();setMessages((m)=>[...m,{role:'assistant',content:data.reply||data.error||'No answer was available.',sources:data.sources||[]}]);}catch{setMessages((m)=>[...m,{role:'assistant',content:'Network error. Email hello@hellokritrna.com.'}]);}finally{setBusy(false)}}
 return <div className="ask-page-panel"><div className="ask-disclaimer">Educational company information only. No medical advice. Do not submit medical records, genetic reports or proprietary sequences.</div><div className="ask-messages" aria-live="polite">{messages.map((message,index)=><div key={index} className={`ask-message ${message.role}`}><p>{message.content}</p>{message.sources?.length?<div className="ask-sources">{message.sources.map((source)=><a key={source.id} href={source.href}>{source.title} ↗</a>)}</div>:null}</div>)}{busy&&<p className="ask-loading">Checking approved sources…</p>}</div>{messages.length===1&&<div className="ask-suggestions">{SUGGESTIONS.map((item)=><button key={item} onClick={()=>void send(item)}>{item}</button>)}</div>}<div className="ask-compose"><label htmlFor="ask-page-input">Your question</label><textarea id="ask-page-input" value={input} maxLength={900} onChange={(e)=>setInput(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}}} /><button className="btn btn-solid" onClick={()=>void send()} disabled={busy||!input.trim()}>Send</button></div></div>;
}
