'use client';
import { motion, useReducedMotion } from 'framer-motion';
import type { CSSProperties } from 'react';
export function AmbientSignals(){const r=useReducedMotion();return <div className="ambient-signals" aria-hidden>{[0,1,2,3,4,5].map(i=><motion.i key={i} animate={r?undefined:{y:[0,-18-i*2,0],opacity:[.12,.32,.12]}} transition={{duration:12+i*2,repeat:Infinity,ease:'easeInOut',delay:i*.7}}/>)}</div>}
export function BridgeWorld(){const r=useReducedMotion();return <div className="bridge-world" aria-hidden><motion.div className="bridge bridge-left" initial={{x:-38,opacity:0}} animate={{x:0,opacity:1}} transition={{duration:1.2}}><span/></motion.div><motion.div className="bridge-key" animate={r?undefined:{y:[0,-10,0],rotate:[-1,1,-1]}} transition={{duration:6,repeat:Infinity,ease:'easeInOut'}}/><motion.div className="bridge bridge-right" initial={{x:38,opacity:0}} animate={{x:0,opacity:1}} transition={{duration:1.2}}><span/></motion.div><div className="bridge-caption stop">interruption</div><div className="bridge-caption continue">continuation</div></div>}
const GATES=['Processing','Structure','Context','Safety'];
export function FilterWorld(){const r=useReducedMotion();return <div className="filter-world" aria-hidden><div className="input-rays">{Array.from({length:18},(_,i)=><motion.i key={i} animate={r?undefined:{opacity:[.18,.58,.18]}} transition={{duration:3+i*.12,repeat:Infinity,delay:i*.08}} style={{'--ray':i} as CSSProperties}/>)}</div><div className="gates">{GATES.map((g,i)=><motion.div key={g} className="gate" initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.12}}><span>{g}</span><b/></motion.div>)}</div><div className="output-rays"><i/><i/><i/></div></div>}
export function ProgrammeWorld({kind}:{kind:'fibre'|'tension'|'guardian'}){const r=useReducedMotion();return <div className={`programme-world ${kind}`} aria-hidden><motion.div className="fragment top" animate={r?undefined:{y:[0,-7,0]}} transition={{duration:6.5,repeat:Infinity,ease:'easeInOut'}}/><motion.div className="programme-key" animate={r?undefined:{scale:[.96,1.04,.96],opacity:[.72,1,.72]}} transition={{duration:4.8,repeat:Infinity,ease:'easeInOut'}}/><motion.div className="fragment bottom" animate={r?undefined:{y:[0,7,0]}} transition={{duration:7.2,repeat:Infinity,ease:'easeInOut'}}/></div>}
export function ConstellationWorld(){const r=useReducedMotion();return <div className="constellation" aria-hidden>{Array.from({length:34},(_,i)=><motion.i key={i} style={{left:`${8+((i*37)%84)}%`,top:`${9+((i*53)%78)}%`}} animate={r?undefined:{opacity:[.18,i%7===0?.9:.36,.18],scale:[1,1.35,1]}} transition={{duration:5+(i%6),repeat:Infinity,delay:(i%9)*.25}}/>)}<span>India-originated science · globally connected</span></div>}
