import Link from 'next/link';
import EvidenceCarousel from '@/components/EvidenceCarousel';

export function ModalityEvidence() {
  return <section className="evidence-band"><div className="wrap">
    <div className="evidence-head"><div><div className="eyebrow">Mechanistic comparison</div><h2>Why suppressor tRNA is a distinct modality.</h2><p className="evidence-subcopy">The case is not that every other modality is wrong. It is that each intervenes at a different biological layer, and suppressor tRNA uniquely combines a defined amino acid, a defined premature stop and no permanent DNA edit.</p></div></div>
    <div className="evidence-comparison"><table><thead><tr><th>Modality</th><th>Structural advantage</th><th>Primary development challenge</th></tr></thead><tbody>
      <tr className="highlight"><td>Suppressor tRNA</td><td>Defined amino acid; codon-specific; potentially reusable across genes</td><td>Charging, transcript context, binding-tissue delivery and native-stop safety</td></tr>
      <tr><td>Small-molecule readthrough</td><td>Drug-like administration and broad access to translation</td><td>Context dependence and limited control of inserted amino-acid identity</td></tr>
      <tr><td>RNA editing</td><td>Repairs the RNA message without changing DNA</td><td>Guide-per-variant design, editable-base constraints and bystander risk</td></tr>
      <tr><td>DNA editing</td><td>Potentially durable correction</td><td>Irreversibility, edit specificity and delivery complexity</td></tr>
      <tr><td>Gene replacement</td><td>Supplies a functional coding payload</td><td>Payload size, expression control, immune response and tissue delivery</td></tr>
    </tbody></table></div>
    <p className="evidence-caption">Public positioning only. Modality outcomes vary by disease, construct, delivery system, tissue and assay.</p>
  </div></section>;
}

export function FourGatesEvidence() {
  const gates = [
    ['01','Charging','Is the engineered tRNA charged with the intended amino acid in human cells?','Only 2 of 20 synthetase-level identity calls in the reviewed set rest directly on human evidence.','var(--magenta)'],
    ['02','Transcript context','Does activity survive the real disease transcript, NMD state and local termination context?','Reporter systems can differ sharply from endogenous and programmed-readthrough contexts.','var(--cyan)'],
    ['03','Binding-tissue delivery','Can the payload reach the cell that actually produces the therapeutic protein?','Across the reviewed disease set, structured-small-RNA evidence remains rodent-level or absent at the weakest required tissue.','var(--forest)'],
    ['04','Native-stop safety','Can premature stops be decoded without unacceptable extension at normal stops?','Native-stop effects were assessed in only 22 of 200 published constructs; detection floors were rarely stated.','var(--violet)'],
  ];
  return <section className="evidence-band dark"><div className="wrap"><div className="evidence-head"><div><div className="eyebrow">The four scientific gates</div><h2>Readthrough is the beginning of the question, not the end.</h2><p className="evidence-subcopy">A credible programme must clear all four gates. A strong result on one cannot compensate for failure on another.</p></div><Link className="btn btn-ghost" href="/evidence" style={{borderColor:'var(--cream)',color:'var(--cream)'}}>Evidence standards →</Link></div><div className="evidence-gates">{gates.map(([n,t,p,value,color])=><article className="evidence-gate" key={t} style={{'--gate-accent':color} as React.CSSProperties}><b>Gate {n}</b><h3>{t}</h3><p>{p}</p><div className="gate-number">{value}</div><div className="gate-note">Current reviewed evidence; not a KritRNA efficacy claim</div></article>)}</div></div></section>;
}

export function ReportingEvidence() {
  return <section className="evidence-band"><div className="wrap"><div className="evidence-head"><div><div className="eyebrow">Evidence audit</div><h2>The field’s published record is promising—and incomplete where candidate decisions matter most.</h2><p className="evidence-subcopy">KritRNA’s standard is to keep assay identity, denominator, source and limitation attached to every quantitative result.</p></div></div><div className="evidence-stats">
    <div className="evidence-stat-card"><strong>200</strong><span>published constructs audited</span><small>Across 44 PMIDs and 301 condition rows</small></div>
    <div className="evidence-stat-card"><strong>11%</strong><span>assessed native-stop effects</span><small>22 of 200 constructs</small></div>
    <div className="evidence-stat-card"><strong>1.5%</strong><span>stated a detection floor</span><small>3 of 200 constructs; zero without a floor is ambiguous</small></div>
    <div className="evidence-stat-card"><strong>17.5%</strong><span>confirmed inserted amino acid</span><small>35 of 200 constructs; targeted MS is the decisive assay class</small></div>
  </div><div className="evidence-callout"><h3>The standard we intend to raise</h3><p>Reporter activity is a development signal, not final proof. Lead decisions require endogenous full-length protein, mutant-RNA/NMD measurement, amino-acid identity, disease-relevant function and quantified native-stop safety.</p></div></div></section>;
}

export function PlatformEvidence() {
  const slides = [
    {kicker:'Data reality',title:'Public scale is not the same as independent biological evidence.',body:'In the reviewed inventory, approximately 99.7% of harmonisable percent-readthrough measurements came from two libraries in one paper and laboratory. Random splits can therefore reward study recognition rather than biological generalisation.',note:'Public data can support priors and feature discovery; it cannot yet establish a prospectively validated design engine.',accent:'var(--magenta)'},
    {kicker:'What exists today',title:'An evidence-to-decision architecture.',body:'The current asset is the disciplined connection between controlled identifiers, source permissions, assay-aware evidence, biological constraints, explicit uncertainty and programme decisions.',note:'No public claim of validated therapeutic prediction.',accent:'var(--cyan)'},
    {kicker:'What must be earned',title:'Proprietary same-assay biology and prospective validation.',body:'Defensibility compounds when experimental outcomes are commensurable, complete scaffold and context groups are held out, and candidate ranking succeeds prospectively rather than retrospectively.',note:'Exact benchmark allocation and candidate designs remain confidential.',accent:'var(--forest)'},
  ];
  return <section className="evidence-band"><div className="wrap"><div className="evidence-head"><div><div className="eyebrow">Platform evidence</div><h2>Build the learning system around biology—not around a flattering split.</h2></div></div><EvidenceCarousel slides={slides}/></div></section>;
}

export function ProgrammeEvidence() {
  const axes=['Mechanism suitability','Restoration threshold','NMD tractability','Structured-RNA delivery','Competitive whitespace','Regulatory precedent','Indian burden and ascertainment'];
  return <section className="evidence-band"><div className="wrap"><div className="evidence-head"><div><div className="eyebrow">Programme selection</div><h2>Seven non-compensatory axes. No cosmetic composite score.</h2><p className="evidence-subcopy">A favourable axis records that a defined condition was met. It does not cancel a failed delivery route, an unsuitable mechanism or an unmeasurable restoration threshold.</p></div><Link className="btn btn-ghost" href="/explorer">Open disease explorer →</Link></div><div className="evidence-columns"><div className="evidence-panel"><div className="label">The seven questions</div><h3>Every programme must survive the full decision chain.</h3><div className="evidence-list">{axes.map((axis,i)=><div key={axis}><span>{String(i+1).padStart(2,'0')}</span><b>{axis}</b></div>)}</div></div><div className="evidence-panel"><div className="label">Current aggregate result</div><h3>The screen is doing its job.</h3><p>No disease in the 40-disease review passed every axis under current public evidence. One reached six favourable axes and seven reached five. The result identifies exactly which dependency must be resolved before a programme advances.</p><div className="evidence-stats" style={{gridTemplateColumns:'repeat(2,1fr)',marginTop:20}}><div className="evidence-stat-card"><strong>0/40</strong><span>passed all seven</span><small>Not a claim that no disease is viable</small></div><div className="evidence-stat-card"><strong>22/40</strong><span>delivery evidence adverse</span><small>Weakest required tissue; rodent evidence is not solved delivery</small></div></div></div></div></div></section>;
}

export function IndiaEvidence() {
  return <section className="evidence-band"><div className="wrap"><div className="evidence-head"><div><div className="eyebrow">India as a scientific variable</div><h2>The gap is measurable. The response must be built.</h2><p className="evidence-subcopy">Clinical reports and population-frequency records are kept separate because they measure different things. Neither is converted into patient counts or national prevalence.</p></div></div><div className="evidence-columns"><article className="evidence-panel"><div className="label">Ascertainment</div><h3>Indian evidence is concentrated, not comprehensive.</h3><div className="evidence-stats" style={{gridTemplateColumns:'repeat(2,1fr)',marginTop:18}}><div className="evidence-stat-card"><strong>1.58%</strong><span>Indian submitters</span><small>Within a 14,338-record audit</small></div><div className="evidence-stat-card"><strong>3/6</strong><span>geographic zones represented</span><small>East, Northeast and Central absent in the reviewed submission set</small></div></div></article><article className="evidence-panel"><div className="label">Delivery</div><h3>Global vector defaults may not be Indian defaults.</h3><p>Reviewed Indian cohorts reported high neutralising-antibody prevalence for several AAV capsids, including 89.2% for AAV5 in healthy participants and 100% in one haemophilia cohort. These data make population-aware delivery strategy a design input, not a late commercial adjustment.</p><p className="evidence-caption">Cohort sizes and assay methods vary. Seroprevalence does not by itself prove programme failure.</p></article></div></div></section>;
}

export function InvestorEvidence() {
  const rungs=[['Rung 1 · present','Evidence-to-decision architecture','Controlled identifiers, licensing boundaries, assay-aware evidence and explicit no-go reasons.'],['Rung 2 · to earn','Proprietary commensurable biology','Human-cell charging, endogenous protein/function and quantified safety in consistent assays.'],['Rung 3 · to earn','Prospective validation','Complete scaffold and context groups held out before candidate ranking.'],['Rung 4 · future','Lead packages','Candidate, delivery, CMC, safety and programme rationale assembled into investable assets.']];
  return <section className="evidence-band"><div className="wrap"><div className="evidence-head"><div><div className="eyebrow">The moat ladder</div><h2>One rung is real today. The next three are defined, bounded value inflections.</h2><p className="evidence-subcopy">The company is not presenting a finished therapeutic platform. It is presenting a disciplined path for turning scientific uncertainty into proprietary evidence and lead-quality decisions.</p></div></div><div className="grid cols-4">{rungs.map(([k,t,p],i)=><article className="cell" key={t} style={{borderTop:`4px solid ${['var(--magenta)','var(--cyan)','var(--forest)','var(--violet)'][i]}`}}><div className="k">{k}</div><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>;
}
