import Link from 'next/link';
import Image from 'next/image';
import Reveal from '@/components/Reveal';
import MolecularHero from '@/components/MolecularHero';
import TranslationStory from '@/components/TranslationStory';
import BrandOrigin from '@/components/BrandOrigin';
import EngineShowcase from '@/components/EngineShowcase';
import {PROGRAMS,TEAM} from '@/lib/content';
import {DEPENDENCIES,PUBLIC_RESEARCH} from '@/lib/publicStory';
const AUDIENCES=[['Families & advocates','Understand premature stop codons, the scientific opportunity and the questions that remain.','/resources','Science in plain language'],['Scientists & development partners','Explore our molecular rationale, developing platform and opportunities for rigorous experimental collaboration.','/partners','Build the evidence with us'],['Investors & strategic partners','Explore the shared-mechanism thesis, programme logic and India-originated biotechnology opportunity.','/investors','Explore the investment thesis'],['Builders of the company','Work across computation, molecular biology, operations and scientific communication.','/careers','Explore open roles']];
export default function Home(){return <div className="editorial-home noir-home">
 <header className="editorial-hero"><div className="hero-grain" aria-hidden="true"/><div className="wrap hero-composition"><div className="hero-copy"><div className="hero-kicker"><span/>INDIA-BUILT · PRECISION TRANSLATION THERAPEUTICS</div><h1>Reading through<br/><em>silence.</em></h1><p className="hero-promise">Restoring the protein.</p><p className="hero-description">Developing AI-guided suppressor-tRNA therapeutics.<br/>For genetic messages that stop too soon.</p><div className="hero-actions"><Link className="editorial-button light-button" href="#the-science">Discover how it works <span aria-hidden="true">↓</span></Link><Link className="text-link" href="/partners">Build with us ↗</Link></div></div><MolecularHero/></div><div className="wrap hero-baseline"><a href="#the-possibility" className="scroll-cue">↓ <span>FOLLOW THE STORY</span></a><span>MOLECULAR SCIENCE <i/> COMPUTATIONAL INTELLIGENCE <i/> HUMAN POSSIBILITY</span><span className="hero-edition">KRITRNA / NOIR</span></div></header>
 <section id="the-possibility" className="manifesto-section"><div className="wrap"><div className="section-index"><span>01 / THE POSSIBILITY</span><span>ENGINEERING THE LANGUAGE OF LIFE</span></div><div className="manifesto-layout"><Reveal><h2 className="display-heading">The message<br/>is interrupted.<br/><em>The possibility<br/>is not.</em></h2></Reveal><div className="manifesto-copy"><Reveal><span className="micro accent-text">WHY KRITRNA EXISTS</span><p className="large-body">Our cells carry instructions for making proteins. Sometimes, a single mutation tells the cell to stop before the work is complete.</p><p>KritRNA is building a suppressor-tRNA therapeutics platform for selected nonsense-mutation contexts. We combine molecular biology, evidence-led programme selection and computational translation science to explore where restoring full-length protein could make a meaningful difference.</p><Link className="underline-link" href="/problem">Understand the molecular challenge ↗</Link></Reveal><div className="mission-footnote"><span className="status-dot"/>DISCOVERY-LED. EVIDENCE-GUIDED. INDIA-BUILT.</div></div></div></div></section>
 <section className="reading-section" id="the-science"><div className="wrap"><div className="section-index"><span>02 / LEARN THE SCIENCE</span><span>FROM THE MESSAGE TO THE PROTEIN</span></div><div className="reading-intro"><Reveal><h2 className="display-heading">A cell reads its instructions<br/><em>three letters at a time.</em></h2></Reveal><Reveal><p className="large-body">DNA stores the instructions. mRNA carries a working copy. The ribosome reads it. tRNA connects the code to the amino acids that build a protein.</p><p>A tRNA is a single RNA chain folded into an adaptor, with parts of the same chain paired into stems. One end carries an amino acid; the other helps recognise a codon on the message. At a normal stop, release factors end translation.</p></Reveal></div><Reveal><TranslationStory/></Reveal><div className="failure-pair"><Reveal><article><span className="micro">ONE MUTATION</span><h3>The protein can end too early.</h3><p>A nonsense mutation turns a sense codon into a premature stop. Translation may produce a shortened protein with reduced, absent or altered function.</p></article></Reveal><Reveal><article><span className="micro">A SECOND, CONTEXT-DEPENDENT FAILURE</span><h3>The message can be lost.</h3><p>Nonsense-mediated decay can reduce the transcript before enough protein is made. Readthrough and message survival are connected questions that need to be studied together.</p></article></Reveal></div><div className="science-callout"><span className="micro">THE THERAPEUTIC IDEA</span><p>Help translation continue—without editing the DNA sequence.</p><span>Our approach acts during protein synthesis. Its duration, dosing and effects depend on how the candidate is designed and delivered.</span></div><div className="science-sources">Scientific background: <a href="https://www.rcsb.org/structure/1EHZ" target="_blank" rel="noreferrer">Reference tRNA structure ↗</a><a href={PUBLIC_RESEARCH.href} target="_blank" rel="noreferrer">Published suppressor-tRNA research ↗</a></div></div></section>
 <section className="dependencies-section"><div className="wrap"><div className="section-index"><span>03 / WHAT HAS TO WORK</span><span>CONNECTED CONDITIONS, NOT ISOLATED SCORES</span></div><Reveal><h2 className="display-heading smaller">Four conditions.<br/><em>One biological context.</em></h2><p className="section-lead">A molecule cannot succeed on design alone. Charging, termination competition, message survival and delivery have to be considered together.</p></Reveal><div className="dependency-list">{DEPENDENCIES.map(([n,title,question,body])=><Reveal key={n}><article><span className="dependency-number">{n}</span><div><span className="micro">{title}</span><h3>{question}</h3><p>{body}</p></div></article></Reveal>)}</div><div className="safety-band"><span className="micro">SAFETY ACROSS EVERY CONDITION</span><p>Useful protein function, normal-stop fidelity and cellular response matter alongside readthrough activity. They are part of the evidence—not optional checks at the end.</p></div></div></section>
 <EngineShowcase/>
 <section className="programmes-section" id="programmes"><div className="wrap"><div className="section-index"><span>04 / RESEARCH PROGRAMMES</span><span>EARLY RESEARCH · PROGRAMME DEFINITION</span></div><div className="programmes-intro"><Reveal><h2 className="display-heading">A shared error class.<br/><em>Distinct biological questions.</em></h2></Reveal><Reveal><p>A premature stop in a different gene can create a different disease. Our initial focus is selected nonsense-mutation contexts in HBB, DMD and TP53. Each programme has its own protein-restoration, delivery and safety questions.</p></Reveal></div><div className="programme-list">{PROGRAMS.map((p,i)=><Reveal key={p.gene}><details className="programme-row" open={i===0}><summary><span className="programme-count">0{i+1}</span><span className="programme-title"><span className="micro">{p.area}</span><span>{p.name}</span></span><span className="gene-tag">{p.gene}</span><span className="programme-expand" aria-hidden="true">+</span></summary><div className="programme-detail"><p>{p.goal}</p><div><span className="micro">CURRENT MILESTONE</span><p>{p.stage}</p></div><div><span className="micro">NEXT EVIDENCE GATE</span><p>{p.next}</p></div></div></details></Reveal>)}</div><Link href="/pipeline" className="underline-link">Explore the research programmes ↗</Link></div></section>
 <BrandOrigin/>
 <section className="people-section"><div className="wrap"><div className="section-index"><span>05 / PEOPLE & PURPOSE</span><Link href="/about#founding-story">OUR FOUNDING STORY ↗</Link></div><div className="people-layout"><Reveal><div className="people-copy"><h2 className="display-heading smaller">Serious science.<br/><em>Shared purpose.</em></h2><p>KritRNA brings molecular research, computational ambition and patient-centred communication into one company. Our founders are building from India, with a scientific outlook that crosses borders.</p><Link href="/about#founding-story" className="underline-link">Why we are building KritRNA ↗</Link><Link href="/team" className="underline-link">Our team and scientific network ↗</Link></div></Reveal><div className="founder-pair">{[TEAM.lead,TEAM.outreach].map(p=><Reveal key={p.name}><Link href="/team" className="founder-card"><div className="founder-photo"><Image src={p.photo} alt={p.name} width={420} height={500} sizes="(max-width: 640px) 44vw, 280px"/></div><h3>{p.name}</h3><p>{p.role}</p></Link></Reveal>)}</div></div></div></section>
 <section className="evidence-editorial"><div className="wrap"><div className="section-index"><span>06 / THE SCIENTIFIC FOUNDATION</span><Link href="/evidence">EXPLORE THE EVIDENCE HUB ↗</Link></div><div className="evidence-layout"><Reveal><h2 className="display-heading smaller">Ambition, grounded<br/><em>in the evidence.</em></h2><p>The better question is not only whether readthrough can happen. It is which candidate to test, in which context, and what evidence would justify the next step.</p></Reveal><Reveal><span className="micro">PUBLISHED ACADEMIC RESEARCH</span><h3 className="research-title">{PUBLIC_RESEARCH.title}</h3><p>{PUBLIC_RESEARCH.authors}<br/>{PUBLIC_RESEARCH.venue}</p><p className="scene-note">{PUBLIC_RESEARCH.note}</p><a href={PUBLIC_RESEARCH.href} className="underline-link" target="_blank" rel="noreferrer">Read the open-access paper ↗</a></Reveal></div></div></section>
 <section className="audience-section"><div className="wrap"><div className="section-index"><span>07 / FIND YOUR WAY IN</span><span>DIFFERENT PERSPECTIVES. ONE MISSION.</span></div><div className="audience-list">{AUDIENCES.map(([title,text,href,action],i)=><Reveal key={title}><Link className="audience-row" href={href}><span className="micro">0{i+1}</span><div><h3>{title}</h3><p>{text}</p><span className="audience-action">{action}</span></div><span className="audience-arrow" aria-hidden="true">↗</span></Link></Reveal>)}</div></div></section>
 <section className="closing-section"><div className="closing-orbit" aria-hidden="true"/><div className="wrap"><Reveal><span className="micro">BUILD THE NEXT CHAPTER</span><h2 className="display-heading">Better questions.<br/><em>Greater possibilities.</em></h2><p>We welcome scientific, CRO, disease-model, delivery and strategic collaborators who want to turn a compelling biological idea into rigorous experimental evidence.</p><div className="closing-actions"><Link className="editorial-button light-button" href="/partners">Scientific or CRO collaboration ↗</Link><Link className="text-link" href="/investors">Investor discussion ↗</Link><Link className="text-link" href="/careers">Join the team ↗</Link></div></Reveal></div></section>
 </div>;}
