'use client';
import {useId,useState} from 'react';
import Link from 'next/link';
import MolecularScene from './MolecularScene';
const chapters=[
 {title:'Normal translation',kicker:'01 / THE MESSAGE IS READ',body:'A ribosome reads mRNA in three-letter codons. Aminoacyl-tRNAs deliver amino acids; the growing chain is extended until release factors recognise a normal stop.',detail:'The highlighted CAG is a sense codon. The ribosome moves along the message from 5′ to 3′.'},
 {title:'A premature stop',kicker:'02 / ONE MUTATION, TWO FAILURES',body:'Here, an illustrative CAG-to-UAG change replaces an amino-acid codon with a premature stop. Release factors can end translation early. Nonsense-mediated decay may also reduce the amount of message available.',detail:'Message decay is context-dependent and is not shown as an inevitable consequence of every premature stop.'},
 {title:'Suppressor tRNA',kicker:'03 / AN OPPORTUNITY TO CONTINUE',body:'An engineered suppressor tRNA can recognise a selected premature stop and carry an amino acid into the ribosome. If it succeeds in competing with termination, the protein chain can continue.',detail:'The molecular poses are a teaching schematic, not a candidate sequence, therapeutic result or exact decoding-cycle simulation.'},
 {title:'Beyond readthrough',kicker:'04 / THE FULL PROTEIN STILL HAS TO WORK',body:'Translation can proceed downstream towards a full-length protein. The development question is whether that protein is correctly made, functional and produced in the right cells, with acceptable effects at normal stop codons.',detail:'Native-stop safety, transcript survival, delivery and protein function require experimental measurement. The native stop shown is UAA.'}
];
export default function TranslationStory(){const [step,setStep]=useState(0),id=useId(),chapter=chapters[step];return <div className="translation-observatory"><div className="observatory-top"><span className="micro">INSIDE THE TRANSLATION MACHINERY</span><span>Explore four chapters</span></div><MolecularScene kind="translation" step={step} label={chapter.title}/><div className="translation-chapters" role="group" aria-label="Translation story chapters">{chapters.map((c,i)=><button key={c.title} type="button" aria-pressed={step===i} aria-controls={id} onClick={()=>setStep(i)}><span>0{i+1}</span>{c.title}</button>)}</div><div className="translation-explanation" id={id} aria-live="polite"><span className="micro">{chapter.kicker}</span><h3>{chapter.title}</h3><p>{chapter.body}</p><p className="scene-note">{chapter.detail}</p></div><Link className="underline-link" href="/science">Read the science in more detail ↗</Link></div>;}
